[github]
owner   = "rust-lang"
project = 59

[colors]
github-name = "Status"
[colors.values]
"To Do"       = "#888888"
"Can Do"      = "#d9b04a"
"In Progress" = "#4a90d9"
"Done"        = "#57a85a"
"Fixed By"    = "#a05ad9"
"Abandoned"   = "#bbbbbb"

[cluster]
github-name = "Priority"
[cluster.values]
"P-critical" = "Critical"
"P-high"     = "High"
"P-medium"   = "Medium"
"P-low"      = "Low"
